services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - xxxx:5432 # change to correct ports on deployment
    environment:
      POSTGRES_USER: xxxx
      POSTGRES_DB: db
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 7s
      timeout: 5s
      retries: 5
    # Set network later
  
  # Healthchecks not added for now
  backend:
    image: ldr-backend
    restart: always
    ports:
      - xxxx:80
    environment:
      POSTGRES_PORT: xxxx
      POSTGRES_USER: xxxx
      POSTGRES_DB: db
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    depends_on:
      db:
        condition: service_healthy

  # Healthchecks not added for now
  frontend:
    image: ldr-frontend
    restart: always
    ports:
      - xxxx:80
    depends_on:
      backend:
        condition: service_started

secrets:
  pg_password:
    file: ./pg_password

volumes:
  postgres-data: