services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - xxxx:5432 # change to correct ports on deployment
    env_file:
      - pg.env
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 7s
      timeout: 5s
      retries: 5
    # Set network later
  
  # Healthchecks not added for now
  backend:
    image: ldr-backend
    restart: always
    ports:
      - xxxx:80
    env_file:
      - pg.env
      - .env
    environment:
      IS_DOCKER: True
    depends_on:
      db:
        condition: service_healthy

  # Healthchecks not added for now
  frontend:
    image: ldr-frontend
    restart: always
    ports:
      - xxxx:80
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres-data: